FROM node:22-alpine3.20 AS build

COPY ../package.json package-lock.json /app/
WORKDIR /app

RUN echo "📦 Устанавливаем зависимости..." && npm ci

COPY .. .

RUN echo "📁 Содержимое /app перед генерацией:" && ls -la

RUN echo "🚀 Собирает build ssr Nuxt 3..." && npm run build

RUN echo "📁 Содержимое .output после генерации:" && ls -la .output
RUN echo "📁 Содержимое .output/public:" && ls -la .output/public
RUN echo "📁 Содержимое .output/server:" && ls -la .output/server

FROM node:22-alpine3.20

WORKDIR /app
COPY --from=build /app/.output .output

RUN echo "🚀 Запуск server..."

EXPOSE 3000
CMD node /app/.output/server/index.mjs